# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'J-Con' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for J-Con

  pod 'lottie-ios', '3.4.3'
  pod 'iOSDropDown'
  pod 'IQKeyboardManagerSwift', '6.5.11'

end
